### ISSUE TITLE
InfiniteHits: error trying to retrieve page greater than one

### ISSUE THREAD

**Issue by Kikobeats** [algolia/react-instantsearch#239]
Hello!

I detected this problem time ago, but I didn't find a way to isolate it. But now yes!!

## How to reproduce it

1. Clone nextjs example

```
curl https://codeload.github.com/algolia/react-instantsearch/tar.gz/master | tar -xz --strip=2 react-instantsearch-master/packages/react-instantsearch/examples/next-app
```

2. Use `InfiniteHits` instead of `Hits`

https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch/examples/next-app/components/app.js#L72

3. Run the application, it will works fine at first time, bu,t if you try to get a page different to `page=1`, like:

```
http://localhost:3000/?page=2
```

The connector can't handle it:

```
Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at InfiniteHits.render (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-instantsearch/src/components/InfiniteHits.js:56:30)
    at /Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:795:21
    at measureLifeCyclePerf (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:794:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/Users/josefranciscoverdugambin/Downloads/react-instantsearch/examples/next-app/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
```

**Comment by mthuret** [comment]
Hi @Kikobeats 

The `Infinite Hits` doesn't play well with Pagination yet. It means that you shouldn't have a Pagination widget on a Infinite Scroll page and you also shouldn't save the `page` inside the URL.

I believe that this is also related to #85.

**Comment by Kikobeats** [comment]
Oh, that's true. I close that in favour of #85
