### ISSUE TITLE
Cannot read property 'addAlgoliaAgent' of null

### ISSUE THREAD

**Issue by kwent** [algolia/react-instantsearch#2740]
Hi there, do you you guys have any idea why this error raises ? Regards

react-instantsearch-dom@5.7.0:

```js
import { createInstantSearch } from 'react-instantsearch-dom/server';
import algoliasearch from 'algoliasearch/lite';

const searchClient = algoliasearch(
  process.env.ALGOLIA_APP_ID,
  process.env.ALGOLIA_API_KEY
);

export const { InstantSearch, findResultsState } = createInstantSearch(
  searchClient
);
```

```
TypeError: Cannot read property 'addAlgoliaAgent' of null
    at new AlgoliaSearchHelper (/Users/kwent/Projects/project/project.com/node_modules/algoliasearch-helper/src/algoliasearch.helper.js:122:14)
    at algoliasearchHelper (/Users/kwent/Projects/project/project.com/node_modules/algoliasearch-helper/index.js:40:10)
    at default (/Users/kwent/Projects/project/project.com/build/server/webpack:/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:125:1)
    at findResultsState (/Users/kwent/Projects/project/project.com/build/server/webpack:/app/server.js:93:5)
```

Something looks off here and client looks like initialized to `null` every single time ? https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-dom/src/core/createInstantSearchServer.js#L105

**Comment by Haroenv** [comment]
Hi @kwent, you are getting this, because the app you are rendering does not have the prop `searchClient` on the `InstantSearch`. The error is somewhat confusing, since `createInstantSearch` accepts a searchClient, but it's still required. 

working full (minimal) example: 

```js
const React = require('react');
const ReactDOM = require('react-dom/server');
const { createInstantSearch } = require('react-instantsearch-dom/server');
const algoliasearch = require('algoliasearch/lite.js');

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76'
);

const { InstantSearch, findResultsState } = createInstantSearch();

const App = ({ resultsState }) =>
  React.createElement(
    'div',
    {},
    React.createElement(
      InstantSearch,
      {
        indexName: 'instant_search',
        searchClient,
        resultsState,
      },
      'app'
    )
  );

findResultsState(App).then(resultsState => {
  console.log(resultsState);
  const str = ReactDOM.renderToString(React.createElement(App), {
    resultsState,
  });

  console.log('str', str);
});
```

**Comment by kwent** [comment]
Make sense. Closing
