### ISSUE TITLE
Maximum call stack size exceeded. Related to cache ?

### ISSUE THREAD

**Issue by YoannDelpierre** [algolia/react-instantsearch#2912]
**Describe the bug 🐛**

I got a 500 from SSR response. In my log I get `RangeError: Maximum call stack size exceeded`

**To Reproduce 🔍**
 
Infortunately, I have only this problem on production, not on staging or local.

If I restart my instance, everything back to normal. My memory was around 25%, I have a total o 2040 mo for my instance.

So I assume it's a problem on Algolia's cache.

**Environment:**

Next JS 9.3.4, Algolia javascript 4.1, ReactInstantSearch 6.4.0.

Never had the problem with Algolia 3.35.1 and ReactInstanceSearch 6.3.0

**Additional context**

```
14:30:24
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
14:30:24
at client.search (/usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:344:50)
14:30:24
at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29
14:30:24
at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)
```

**Comment by Haroenv** [comment]
Please make a reproducible example @YoannDelpierre, we have a template available for that purpose [here](https://codesandbox.io/s/github/algolia/react-instantsearch/tree/master/examples/server-side-rendering). Thanks!

**Comment by YoannDelpierre** [comment]
Infortunately I can't, because it will expose my data.

```
{"log":"RangeError: Maximum call stack size exceeded\n","stream":"stderr","time":"2020-04-07T08:45:49.092543019Z"}
{"log":"    at String.replace (\u003canonymous\u003e)\n","stream":"stderr","time":"2020-04-07T08:45:49.092568066Z"}
{"log":"    at encode (/usr/src/app/node_modules/@algolia/transporter/dist/transporter.cjs.js:369:19)\n","stream":"stderr","time":"2020-04-07T08:45:49.09257121Z"}
{"log":"    at /usr/src/app/node_modules/@algolia/transporter/dist/transporter.cjs.js:385:21\n","stream":"stderr","time":"2020-04-07T08:45:49.092573699Z"}
{"log":"    at Array.map (\u003canonymous\u003e)\n","stream":"stderr","time":"2020-04-07T08:45:49.092576049Z"}
{"log":"    at Object.serializeQueryParameters (/usr/src/app/node_modules/@algolia/transporter/dist/transporter.cjs.js:385:10)\n","stream":"stderr","time":"2020-04-07T08:45:49.092578296Z"}
{"log":"    at /usr/src/app/node_modules/@algolia/client-search/dist/client-search.cjs.js:399:37\n","stream":"stderr","time":"2020-04-07T08:45:49.092580601Z"}
{"log":"    at Array.map (\u003canonymous\u003e)\n","stream":"stderr","time":"2020-04-07T08:45:49.092582675Z"}
{"log":"    at /usr/src/app/node_modules/@algolia/client-search/dist/client-search.cjs.js:396:34\n","stream":"stderr","time":"2020-04-07T08:45:49.092594457Z"}
{"log":"    at /usr/src/app/node_modules/react-instantsearch-core/dist/cjs/core/createInstantSearchManager.js:348:29\n","stream":"stderr","time":"2020-04-07T08:45:49.092596711Z"}
{"log":"    at Object.get (/usr/src/app/node_modules/@algolia/cache-common/dist/cache-common.cjs.js:43:27)\n","stream":"stderr","time":"2020-04-07T08:45:49.09259898Z"}
```

It seems I have an error on serialize my query parameters :(

**Comment by Haroenv** [comment]
You can remove the appId & apiKey and use the credentials in the example I sent you @YoannDelpierre

**Comment by YoannDelpierre** [comment]
Problem is that it's coming after lots of requests. We reproduce the problem on a sandbox by spamming it. After 4k requests, we got the 500 and the log associated above.

**Comment by Haroenv** [comment]
could you  make clear and easy to reproduce instructions for that please? It seems quite related to your particular setup

**Comment by Haroenv** [comment]
glad you found your solution @YoannDelpierre, can you explain what was the issue?

**Comment by YoannDelpierre** [comment]
hey @Haroenv , I'm using

```
    responsesCache: createInMemoryCache(),
    requestsCache: createInMemoryCache({ serializable: false })
```
Looks like the serializer does not like some requests 🤷‍♂️

**Comment by Haroenv** [comment]
Very weird, I'd still love it if you could create a minimal reproduction for this. Cc @nunomaduro

**Comment by YoannDelpierre** [comment]
Hi @Haroenv, I finally got again the same problem as before.

It appears only after few days on production. One "better" thing today that it was the problem appears only on results when page parameters was out of range result

I can try to make a codesandbox, but we will have not the same env as we have in production (aws environment).

**Comment by kjetilhau** [comment]
I am experiencing the exact same issue after many requests. @YoannDelpierre Did you find a solution?

**Comment by YoannDelpierre** [comment]
@kjetilhau No I did not find a solution.. For now, I'm lucky, I deploy every day so my cache is cleaned.

I think you're right, the official example has not been load tested.

@Haroenv can you check with your team to load test your next js example ? 🙏

**Comment by stuart-williams** [comment]
Tried using the null cache but still getting `Maximum call stack size exceeded` with only light traffic.

```js
const searchClient = algoliasearch(	
    "xxx",	
    "xxx",	
    {	
        requestsCache: createNullCache(),	
        responsesCache: createNullCache()	
    }	
);
```

**Comment by YoannDelpierre** [comment]
@stuart-williams are you using next.js too ?

**Comment by stuart-williams** [comment]
> @stuart-williams are you using next.js too ?

Yes we are using next.js

**Comment by YoannDelpierre** [comment]
@Haroenv @nunomaduro if you have free time for trying to test load your nextjs app 🙏

**Comment by nunomaduro** [comment]
I am off today.  I will dive into this next Friday. @Haroenv Meanwhile maybe you can jump? Otherwise only Friday I will have time.

**Comment by Haroenv** [comment]
I've looked into this before, but wasn't able to reproduce it. Is there a step-by-step to clone and some way to efficiently load-test it?

**Comment by YoannDelpierre** [comment]
We load test with Locust, python tool, on our side

**Comment by YoannDelpierre** [comment]
We test directly on your nextjs example with locust

![image](https://user-images.githubusercontent.com/1655301/81827190-d0158580-9538-11ea-9355-c3eb263b968a.png)

**Comment by nunomaduro** [comment]
Going to tackle this. Gonna get back to you guys once I find the problem.

**Comment by nunomaduro** [comment]
Feedback: I've identified the problem, and we are now working on the solution. Most likely will be deployed on only next Monday because it's Friday.

**Comment by YoannDelpierre** [comment]
Thanks a lot @nunomaduro 

Have a good week-end

**Comment by YoannDelpierre** [comment]
Thanks. Just bump my version and deploy soon 🤞

**Comment by nunomaduro** [comment]
@YoannDelpierre Tell me how it goes. 🤞

**Comment by YoannDelpierre** [comment]
@nunomaduro it's working, thanks a lot for your PR.

My memory is very stable right now.
