### ISSUE TITLE
BUG - Detected multiple renderers concurrently rendering the same context provider (React 18.0.0?)

### ISSUE THREAD

**Issue by DB-Alex** [algolia/react-instantsearch#3441]
## 🐛 Bug description

I get the following warning on the server side in react when i use:

import { findResultsState } from 'react-instantsearch-dom/server';

Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at Index (node_modules/react-instantsearch-core/dist/cjs/widgets/Index.js:86:34)
    at IndexWrapper (node_modules/react-instantsearch-core/dist/cjs/widgets/Index.js:157:31)

Modules in package.json:

"react": "^18.0.0",
"react-dom": "^18.0.0",
"algoliasearch": "^4.13.0",
"react-instantsearch-dom": "^6.23.3",

**Comment by francoischalifour** [comment]
Can you please reproduce the behavior in this [React InstantSearch Server sandbox](https://codesandbox.io/s/pedantic-danilo-0l9glx?file=/src/server.js)?

**Comment by DB-Alex** [comment]
```
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at InstantSearch (node_modules/react-instantsearch-core/dist/cjs/widgets/InstantSearch.js:101:34)
    at MainIndex (webpack-internal:///(api)/./src/components/organisms/MainIndex/MainIndex.js:18:22)
    at ServerSearchResults (webpack-internal:///(api)/./src/components/molecules/ServerSearchResults/ServerSearchResults.js:21:32)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at InstantSearch (node_modules/react-instantsearch-core/dist/cjs/widgets/InstantSearch.js:101:34)
    at MainIndex (webpack-internal:///./src/components/organisms/MainIndex/MainIndex.js:18:22)
    at LoadableImpl (node_modules/next/dist/shared/lib/loadable.js:84:40)
    at InstantSearchProvider (webpack-internal:///./src/providers/InstantSearchProvider/InstantSearchProvider.js:27:34)
    at LoadableImpl (node_modules/next/dist/shared/lib/loadable.js:84:40)
    at Page (webpack-internal:///./pages/[...rewrite].js:58:17)
    at CartProvider (webpack-internal:///./src/providers/CartProvider/CartProvider.js:76:25)
    at UserProvider (webpack-internal:///./src/providers/UserProvider/UserProvider.js:33:25)
    at ErrorHandlerProvider (webpack-internal:///./src/providers/ErrorHandlerProvider/ErrorHandlerProvider.js:34:9)
    at AppStateProvider (webpack-internal:///./src/providers/AppStateProvider/AppStateProvider.js:20:29)
    at SWRConfig$1 (file://node_modules/swr/dist/index.mjs:495:23)
    at InnerThemeProvider (node_modules/@mui/system/ThemeProvider/ThemeProvider.js:29:39)
    at ThemeProvider (node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:55:5)
    at ThemeProvider (node_modules/@mui/system/ThemeProvider/ThemeProvider.js:49:5)
    at App (webpack-internal:///./pages/_app.js:64:11)
    at StyleRegistry (node_modules/styled-jsx/dist/index/index.js:671:34)
    at FlushEffectContainer (node_modules/next/dist/server/render.js:423:37)
    at AppContainer (node_modules/next/dist/server/render.js:438:29)
    at AppContainerWithIsomorphicFiberStructure (node_modules/next/dist/server/render.js:469:57)
    at div
    at Body (node_modules/next/dist/server/render.js:733:21)
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported.
    at Index (node_modules/react-instantsearch-core/dist/cjs/widgets/Index.js:86:34)
    at IndexWrapper (node_modules/react-instantsearch-core/dist/cjs/widgets/Index.js:157:31)
    at Index (webpack-internal:///./src/components/organisms/Index/index.js:21:18)
    at BlockProductsOverview (webpack-internal:///./src/components/molecules/BlockProductsOverview/BlockProductsOverview.js:52:34)
    at LoadableImpl (node_modules/next/dist/shared/lib/loadable.js:84:40)
    at Block (webpack-internal:///./src/components/organisms/Block/Block.js:13:18)
    at div
    at node_modules/@emotion/react/dist/emotion-element-e89f38a3.cjs.dev.js:72:25
    at Row (webpack-internal:///./src/components/atoms/Row/Row.js:13:16)
    at BlocksPage (webpack-internal:///./src/templates/BlocksPage/BlocksPage.js:44:23)
    at div
    at node_modules/@emotion/react/dist/emotion-element-e89f38a3.cjs.dev.js:72:25
    at MobileWrapper (webpack-internal:///./src/components/atoms/MobileWrapper/MobileWrapper.js:13:26)
    at Layout (webpack-internal:///./src/components/organisms/Layout/Layout.js:46:19)
    at InstantSearch (node_modules/react-instantsearch-core/dist/cjs/widgets/InstantSearch.js:101:34)
    at MainIndex (webpack-internal:///./src/components/organisms/MainIndex/MainIndex.js:18:22)
    at LoadableImpl (node_modules/next/dist/shared/lib/loadable.js:84:40)
    at InstantSearchProvider (webpack-internal:///./src/providers/InstantSearchProvider/InstantSearchProvider.js:27:34)
    at LoadableImpl (node_modules/next/dist/shared/lib/loadable.js:84:40)
    at Page (webpack-internal:///./pages/[...rewrite].js:58:17)
    at CartProvider (webpack-internal:///./src/providers/CartProvider/CartProvider.js:76:25)
    at UserProvider (webpack-internal:///./src/providers/UserProvider/UserProvider.js:33:25)
    at ErrorHandlerProvider (webpack-internal:///./src/providers/ErrorHandlerProvider/ErrorHandlerProvider.js:34:9)
    at AppStateProvider (webpack-internal:///./src/providers/AppStateProvider/AppStateProvider.js:20:29)
    at SWRConfig$1 (file://node_modules/swr/dist/index.mjs:495:23)
    at InnerThemeProvider (node_modules/@mui/system/ThemeProvider/ThemeProvider.js:29:39)
    at ThemeProvider (node_modules/@mui/private-theming/node/ThemeProvider/ThemeProvider.js:55:5)
    at ThemeProvider (node_modules/@mui/system/ThemeProvider/ThemeProvider.js:49:5)
    at App (webpack-internal:///./pages/_app.js:64:11)
    at StyleRegistry (node_modules/styled-jsx/dist/index/index.js:671:34)
    at FlushEffectContainer (node_modules/next/dist/server/render.js:423:37)
    at AppContainer (node_modules/next/dist/server/render.js:438:29)
    at AppContainerWithIsomorphicFiberStructure (node_modules/next/dist/server/render.js:469:57)
    at div
    at Body (node_modules/next/dist/server/render.js:733:21)
```

Content of InstantSearchProvider.js (don't know if you need this but still)

```js
import { searchStateToUrl } from 'helpers/search';
import { isEmpty, isEqual } from 'lodash';
import Router, { useRouter } from 'next/router';
import qs from 'qs';
import React, { useEffect, useState } from 'react';
import { searchClient } from 'utils/algolia';

export const InstantSearchContext = React.createContext({});

const UPDATE_AFTER = 700;

const InstantSearchProvider = ({
	resultsState,
	children,
}) => {
	let router = useRouter();
	let [state, setState] = useState({
		initialized: false,
		debouncedSetState: null,
		searchState: {},
		resultsState: (!isEmpty(resultsState)) ? resultsState : undefined,
	});

	const updateState = (updatedState) => {
		return setState((prevState) => {
			return {
				...prevState,
				...updatedState,
			};
		});
	};

	const handleSearchStateChange = (searchState) => {
		if (isEqual(state.searchState, searchState)) {
			return;
		}

		clearTimeout(state.debouncedSetState);

		updateState({
			searchState,
			debouncedSetState: setTimeout(() => {
				let { query } = router?.query || {};
				let href = searchStateToUrl({
					searchState,
					query,
				});

				Router.push(href, href, {
					shallow: true,
				});
			}, UPDATE_AFTER),
		});
	};

	useEffect(() => {
		let routerSearchState = qs.parse(router.query)?.indices;

		if (!state.initialized && routerSearchState) {
			updateState({
				searchState: {
					indices: routerSearchState,
				},
				initialized: true,
			});
		}
	}, [router.query, state.initialized]);

	return (
		<InstantSearchContext.Provider
			value={{
				handleSearchStateChange,
				searchClient,
				...state,
			}}
		>
			{children}
		</InstantSearchContext.Provider>
	);
};

export default InstantSearchProvider;

```

**Comment by francoischalifour** [comment]
We can't help you further without any snippets or reproduction. The sandbox I sent you uses React 18 and doesn't have this problem, so this likely comes from your application code.

**Comment by Haroenv** [comment]
Do you have the structure of your InstantSearch application and the part which calls findResultsState at least? I'm wondering if this is because of a reused context provider that would not happen if only the InstantSearch app is passed to findResultsState

**Comment by DB-Alex** [comment]
Sure, here is the algolia utility:

```js
import algoliasearch from 'algoliasearch/lite';
import { asyncForEach } from 'helpers/core';
import { getIndexName } from 'helpers/search';
import { findResultsState as instantSearchFindResultsState } from 'react-instantsearch-dom/server';
import { logger } from 'utils/logging';

export const searchClient = algoliasearch(
	process.env.NEXT_PUBLIC_ALGOLIA_APP_ID,
	process.env.NEXT_PUBLIC_ALGOLIA_API_KEY,
);

export const findResultsState = async(Component, {
	indexName,
	indexes,
	...props
}) => {
	let resultsState = {};

	try {
		let indexesExist = true;

		await asyncForEach([
			indexName,
			...new Set(indexes),
		], async(searchIndex) => {
			searchIndex = getIndexName({
				indexName: searchIndex,
			});

			if (
				!await searchClient.initIndex(searchIndex).exists()
			) {
				indexesExist = searchIndex;
			}
		});

		if (indexesExist === true) {
			indexName = getIndexName({
				indexName,
			});

			resultsState = await instantSearchFindResultsState(Component, {
				searchClient,
				indexName,
				indexes,
				...props,
			});
		} else {
			logger.warning(`utils/algolia - findResultsState() - Index: ${indexesExist} does not exist`);
		}
	} catch (error) {
		logger.error('utils/algolia - findResultsState() - Error', {
			error,
			indexName,
			props,
		});
	}

	return JSON.parse(JSON.stringify(resultsState));
};
```

The "Component" getting passed is ServerSearchResults.js

```js
import Index from 'components/organisms/Index';
import MainIndex from 'components/organisms/MainIndex';
import React from 'react';
import { Hits } from 'react-instantsearch-dom';

const ServerSearchResults = ({
	mainIndex,
	indexName,
	indexes,
	preset,
	hitsPerPage = 24,
	...props
}) => {
	if (indexName) {
		if (!mainIndex) {
			mainIndex = indexName;
		}

		if (!indexes) {
			indexes = [indexName];
		}
	}

	if (!indexes || indexes.length === 0) {
		return null;
	}

	return (
		<MainIndex mainIndex={mainIndex} {...props}>
			{indexes.map((indexName, index) => (
				<Index
					key={`${indexName}-${index}`}
					indexName={indexName}
					preset={preset}
					hitsPerPage={hitsPerPage}
				>
					<Hits
						hitComponent={({ hit }) => (
							<React.Fragment>
								{hit.brand} - {hit.name}
							</React.Fragment>
						)}
					/>
				</Index>
			))}
		</MainIndex>
	);
};

export default ServerSearchResults;
```

**Comment by Haroenv** [comment]
what is in the MainIndex component @DB-Alex ?

**Comment by Haroenv** [comment]
I've managed to reproduce this now with just InstantSearch, but as far as I can tell it has no adverse effects. I wonder how eg. Apollo with a very similar design avoids this warning

**Comment by MrSnufalafogus** [comment]
Any update on this? We are seeing the same issue in our React/Next app after upgrading to React 18.0.0

**Comment by wenche** [comment]
We also have the same issue after the upgrade. The culprit for us seems to be the `getServerState` from r`eact-instantsearch-hooks-server`

**Comment by Haroenv** [comment]
As far as I can tell, this is an incorrect warning from React (https://github.com/facebook/react/issues/22796) and it has no effect apart from giving that warning. Conceptually I haven't found a way to avoid the error except by manually ignoring it

**Comment by Haroenv** [comment]
Hey @Qwal, we are aware of this warning, but it doesn't have an impact on the application, but is a result of React counting two distinct renders that happen subsequently as if they happen concurrently (not the case). You can follow in the react issue linked earlier: https://github.com/facebook/react/issues/22796

**Comment by Haroenv** [comment]
Ah, what you're showing isn't the same issue as this one originally was about. The state not matching between client and server would indeed be an issue. 

When I update the default next example to react 18 it works as expected (https://codesandbox.io/s/admiring-benji-ovjzlk?file=/pages/index.js) so I'm guessing the client mismatch is something due to a specific implementation in the pwa ecom ui template, and thus an issue should be opened there (cc @FabienMotte). I'm not sure yet what the specific issue could be though

The react issue shows up in unit testing, but also in our case of server side rendering with an unneeded warning.

**Comment by hutber** [comment]
@Haroenv  for me, the only issue with this is, it gets stuck in a repeating loop. I have tried to work out how to break out of it but I can't. Which then leads to this error: https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached so I'll need to reset my machine after a little while.

176 after a few seconds :O
![image](https://user-images.githubusercontent.com/1344898/192167822-10b8934a-97fe-4b83-884c-f2a774ef2a39.png)

**Comment by Haroenv** [comment]
@hutber could you open a new issue with reproduction, it seems unrelated
