### ISSUE TITLE
InstantSearch connectors error during SSR in built Next.js >= 12.1.6 apps using React 17

### ISSUE THREAD

**Issue by kfranqueiro** [algolia/react-instantsearch#3544]
## 🐛 Bug description

In recent attempts to upgrade Next.js in an app using InstantSearch, I have found that I can upgrade to Next.js 12.1.5 without issue, but with 12.1.6 or 12.2.0, I encounter errors involving InstantSearch connectors (the kind of error I seem to recall usually getting if a connector is incorrectly used outside of `<InstantSearch>`), specifically when running the built production app (seems to work fine in dev).

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Clone this repo's [next example](https://github.com/algolia/react-instantsearch/tree/master/examples/next)
2. Update the `next` version in `package.json` to `12.1.6` or `12.2.0`
3. Run `yarn && yarn build`
4. Run `yarn start`
5. Browse to localhost:3000
6. See 500 in browser and error in server console

**Live reproduction:**

It's probably more useful to perform the above repro locally, as you may or may not see the server-side error log in the sandbox, but here it is:

https://codesandbox.io/s/react-instantsearch-next-1216-6u2c1w-6u2c1w

## 💭 Expected behavior

Page loads successfully, as it does with Next.js 12.1.5 or earlier

## 🖥 Screenshots

<img width="276" alt="image" src="https://user-images.githubusercontent.com/398379/176586912-dff628e2-8dc7-4cfe-97ec-34eb14fbf79d.png">

Server output (with absolute paths snipped):

```
TypeError: Cannot read property 'store' of undefined
    at Connector.getProvidedProps (.../next/node_modules/react-instantsearch-core/dist/cjs/core/createConnector.js:206:63)
    at new AlgoliaConfigure(Configure) (.../next/node_modules/react-instantsearch-core/dist/cjs/core/createConnector.js:86:32)
    at d (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:320)
    at bb (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (.../next/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at execute (.../next/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:170:32)
    at findResultsState (.../next/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:205:10)
    at getServerSideProps (.../next/.next/server/pages/index.js:284:75)
```

## Environment

- React InstantSearch version: 6.29.0 (also experienced with 6.16.0)
- React version: 17.0.2
- Browser: Any
- OS: Any

**Comment by tc-mccarthy** [comment]
Following as I am experiencing the same problem under the same conditions.

**Comment by FabienMotte** [comment]
Hey @kfranqueiro!

This issue has been fixed by the Vercel team in this PR: https://github.com/vercel/next.js/pull/39221
You should be able to test the fix using Next.js [`v12.2.4-canary.9`](https://github.com/vercel/next.js/releases/tag/v12.2.4-canary.9)
I have forked your sandbox with this version and it's working as expected: https://codesandbox.io/s/react-instantsearch-next-qdnznz

I'll update the Next.js version of the example when Next.js `v12.4.4` gets released.

Thanks!

**Comment by kfranqueiro** [comment]
This is awesome. Thanks so much for digging into this!
